:url-ecma-404: https://ecma-international.org/publications-and-standards/standards/ecma-404
:url-svjson-pages: https://esynr3z.github.io/svjson
:url-svunit: https://github.com/svunit/svunit
:url-json-test-suite: https://github.com/nst/JSONTestSuite
:url-verilator-github: https://github.com/verilator/verilator
:url-antora: https://antora.org
:url-asciidoc: https://asciidoc.org
:url-github-pages: https://pages.github.com
:url-conventional-commits: https://www.conventionalcommits.org/en/v1.0.0
:url-keep-a-changelog: https://keepachangelog.com/en/1.1.0
:url-semantic-versioning: https://semver.org/spec/v2.0.0.html
:url-tests-badge: https://github.com/esynr3z/svjson/actions/workflows/tests.yaml/badge.svg?branch=main
:url-documentation-badge: https://github.com/esynr3z/svjson/actions/workflows/docs.yaml/badge.svg?branch=main

= JSON encoder and decoder in SystemVerilog
:navtitle: Overview

image:{url-tests-badge}[Tests] image:{url-documentation-badge}[Documentation]

The project introduces JSON decoder and encoder in pure SystemVerilog without any external dependencies.

== Features

Implementation follows {url-ecma-404}[ECMA standard] and provides SV package `json_pkg` for convenient integration into any HDL project.

* JSON decoder can parse values from string or file
* JSON encoder can dump values to string or file
* JSON values (object, array, string, number, bool) are represented with collection of wrapper classes
* JSON encoding capability can be added to user classes with collection of interface classes
* Additional classes for encoding SystemVerilog enums and bit vectors of any width
* Error reporting and propagation system inspired by Rust

Known limitations:

* `\b` and `\u` escape sequences are not supported for decoder/encoder
* Nesting depth is limited for decoder (1024 by default, limit is controllable)
* No recursion detection for encoder

Detailed documentaion can be found on {url-svjson-pages}[project's site].

== Integration

* Any simulator with extensive SystemVerilog OOP support required
* No external dependencies
* No defines
* No plusargs

IMPORTANT: The package is developed and tested using Verilator 5.24 only. Support of other simulators is planned, but Verilator still will be the main simulator for project as it is the only viable option to organize CI and opensource flow.

Include directories and sources are expressed as filelists (.f files):

* `incdirs.f` - all include directories
*  `package.f` - all packages (single package, actually)

For convenient integration they are united into single `filelist.f`.

To integrate the package into your code you need:

* Clone `svjson` repository
* Set environment variable `SVJSON_ROOT` with a path to `svjson` root on your filesystem
* Add filelist to your simulator using according arguments, e.g.
** `-f ${SVJSON_ROOT}/src/filelist.f`
** or `-file ${SVJSON_ROOT}/src/filelist.f` depending on your simulator.

Then follow {url-svjson-pages}[User guide] section to get instructions on how to use JSON encoder and decoder in practice.

== Development

HDL flows:

* Code tested with {url-svunit}[SVUnit] using {url-json-test-suite}[JSONTestSuite] and custom tests
* Main simulator for development is {url-verilator-github}[Verilator 5.24]
* [TODO] No linting and code formating tools are used yet

Documentation flows:

* All documentation is written in {url-asciidoc}[Asciidoc]
* Documentation site ({url-github-pages}[Github Pages]) is generated via {url-antora}[Antora]
* [TODO] NaturalDocs generated class reference documentation

Repository flows:

* Git messages follows {url-conventional-commits}[Conventional Commits] specification
* Changelog format follows {url-keep-a-changelog}[Keep a Changelog] specification
* Versioning is based on {url-semantic-versioning}[Semantic Versioning].
