:url-svjson-github: https://github.com/esynr3z/svjson/tree/{page-origin-refname}
:url-svjson-github-blob: https://github.com/esynr3z/svjson/blob/{page-origin-refname}

= User guide

== Integration

* Any simulator with extensive SystemVerilog OOP support required
* No external dependencies
* No defines
* No plusargs

IMPORTANT: The package is developed and tested using Verilator 5.24 only. Support of other simulators is planned, but Verilator still will be the main simulator for project as it is the only viable option to organize CI and opensource flow.

Sources and include directories are expressed as filelist (`.f` file), which are quite standard way of describing compilation unit for many EDA tools. Filelist of the project is {url-svjson-github}/src/filelist.f[`src/filelist.f`].

In order to make filelist portable, all paths are relative to `SVJSON_ROOT` environment variable. It should point to {url-svjson-github}[svjson] repository root in your filesystem.

As a result, integration process consists of several simple steps:

* Clone or copy {url-svjson-github}[svjson] repository
* Set environment variable `SVJSON_ROOT` with a path to the repository root on your filesystem
* Add filelist to your simulator compilation options, e.g. `-f ${SVJSON_ROOT}/src/filelist.f`
* `json_pkg` is ready to be used

== JSON Decoding

== JSON Encoding
