:url-svjson-github: https://github.com/esynr3z/svjson

= User guide

== Integration

* Any simulator with extensive SystemVerilog OOP support required
* No external dependencies
* No defines
* No plusargs

IMPORTANT: The package is developed and tested using Verilator 5.24 only. Support of other simulators is planned, but Verilator still will be the main simulator for project as it is the only viable option to organize CI and opensource flow.

Sources and include directories are expressed as filelists (`.f` files), which are quite standard way of describing sources, include directories, defines, etc. fot many EDA tools. There are three of them:

* `src/incdirs.f` - filelist with all include directories
* `src/package.f` - filelist with a SV package
* `src/filelist.f` - filelist, which is a union of both above for convenient integration

In order to make filelists portable, all paths are relative to `SVJSON_ROOT` environment variable. It should point to {url-svjson-github}[svjson] repository root in your filesystem.

As a result, integration process consists of several simple steps:

* Clone or copy {url-svjson-github}[svjson] repository
* Set environment variable `SVJSON_ROOT` with a path to the repository root on your filesystem
* Add filelist to your simulator compilation options, e.g. `-f ${SVJSON_ROOT}/src/filelist.f`
* `json_pkg` is ready to be used

== JSON Decoding

== JSON Encoding
