= JSON package
esynr3z
v0

== Classes

[plantuml]
....
class json_value

class json_object
json_value <|-- json_object

class json_array
json_value <|-- json_array

class json_string
json_value <|-- json_string

class json_integer
json_value <|-- json_integer

class json_bool
json_value <|-- json_bool

class json_null
json_value <|-- json_null
....

[plantuml]
....
enum json_result_e {
    JSON_OK,
    JSON_ERR
}

class json_result<DATA_T> {
}
....

[plantuml]
....
class json_decoder {
    + {static} from_file(path: const string): json_value
    + {static} from_string(str: const ref string): json_value
    - scan_until_value(str: const ref string, start_idx: input int unsigned): int unsigned
    - parse_object(str: const ref string, start_idx: input int unsigned, end_idx: output int unsigned): json_object
    - parse_array(str: const ref string, start_idx: input int unsigned, end_idx: output int unsigned): json_array
    - parse_string(str: const ref string, start_idx: input int unsigned, end_idx: output int unsigned): json_string
    - parse_integer(str: const ref string, start_idx: input int unsigned, end_idx: output int unsigned): json_integer
    - parse_bool(str: const ref string, start_idx: input int unsigned, end_idx: output int unsigned): json_bool
    - parse_null(str: const ref string, start_idx: input int unsigned, end_idx: output int unsigned): json_null
}
....